
Training fold 1 for deit3_base_patch16_224
Training fold 2 for deit3_base_patch16_224
Training fold 3 for deit3_base_patch16_224
Training fold 4 for deit3_base_patch16_224
Training fold 5 for deit3_base_patch16_224
Traceback (most recent call last):
  File "/home/edramos/Documents/MLOPS/ImageClassification-MFG/main.py", line 369, in <module>
    model, optimizer, scheduler =train_model_kfold(subset_dataset, project_name,architecture, lr,n_splits,epochs, num_classes, batch_size)
  File "/home/edramos/Documents/MLOPS/ImageClassification-MFG/main.py", line 123, in train_model_kfold
    train_loss += loss.item()
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.